substitutions:
  # Can only contain lowercase a-z, 0-9 and hyphens. Can be at most 24 characters long.
  name: "athom-smart-plug-v2"
  # This is the friendly name that can also contain uppercase letters, spaces and other characters.
  friendly_name: "Smart Plug V2"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  room: ""
  relay_restore_mode: RESTORE_DEFAULT_OFF
  # How often data is read
  sensor_update_interval: 10s
  # Current Limit in Amps. AU Plug = 10. IL, BR, EU, UK, US Plug = 16.
  current_limit : "16"
  # Hide the ENERGY sensor that shows kWh consumed, but with no time period associated with it. Resets when device restarted and reflashed.
  hide_energy_sensor: "true"  
  device_description: "Athom Smart Plug V2"
  project_name: "Athom Technology.Smart Plug V2"
  project_version: "2.0.3"
  
esphome:
  min_version: 2024.6.0

logger:
  baud_rate: 0

dashboard_import:
  package_import_url: github://dexn/test-breaking-yaml/athom-smart-plug-v2.yaml@main
  import_full_config: true

packages:
  base_package: github://dexn/test-breaking-yaml/base.yaml@main
  fast_boot_package: github://dexn/test-breaking-yaml/fast_boot.yaml@main

# Dentra Components - Adds 'Platform - Energy Statistics'
# https://github.com/dentra/esphome-components/tree/master/components/energy_statistics
external_components:
  - source: github://dentra/esphome-components

uart:
  rx_pin: RX
  baud_rate: 4800

globals:
  - id: total_energy
    type: float
    restore_value: yes
    initial_value: '0.0'

binary_sensor:
  - platform: gpio
    pin:
      number: 5
      mode: INPUT_PULLUP
      inverted: true
    name: "Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

light:
  - platform: status_led
    name: "Status LED"
    id: Status_led
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO13

sensor:
  - platform: cse7766
    current:
      name: "Current"
      filters:
        - throttle_average: ${sensor_update_interval}
        - lambda: if (x < 0.060) return 0.0; else return x;   #For the chip will report less than 3w power when no load is connected
      on_value_range:
        - above: ${current_limit}
          then:
            - switch.turn_off: relay

    voltage:
      name: "Voltage"
      filters:
        - throttle_average: ${sensor_update_interval}

    power:
      name: "Power"
      id: power_sensor
      filters:
        - throttle_average: ${sensor_update_interval}
        - lambda: if (x < 3.0) return 0.0; else return x;    #For the chip will report less than 3w power when no load is connected

    energy:
      name: "Energy"
      id: energy
      unit_of_measurement: kWh
      filters:
        - throttle: ${sensor_update_interval}
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
      on_value:
        then:
          - lambda: |-
              static float previous_energy_value = 0.0;
              float current_energy_value = id(energy).state;
              id(total_energy) += current_energy_value - previous_energy_value;
              previous_energy_value = current_energy_value;
              id(total_energy_sensor).update();
      internal: ${hide_energy_sensor}

    apparent_power:
      name: "Apparent Power"
      filters:
        - throttle_average: ${sensor_update_interval}

    power_factor:
      name: "Power Factor"
      filters:
        - throttle_average: ${sensor_update_interval}

  - platform: template
    name: "Total Energy"
    id: total_energy_sensor
    unit_of_measurement: kWh
    device_class: "energy"
    state_class: "total_increasing"
    icon: "mdi:lightning-bolt"
    accuracy_decimals: 3
    lambda: |-
      return id(total_energy);
    update_interval: ${sensor_update_interval}

  - platform: total_daily_energy
    name: "Total Energy Today"
    restore: true
    power_id: power_sensor
    unit_of_measurement: kWh
    icon: mdi:hours-24
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
     # Dentra Components - Define the id of the sensor providing 'Total Energy' used
  - platform: "energy_statistics"
    total: total_energy_sensor

     # Dentra Components - Adds Energy Yesterday
    energy_yesterday:
      name: "Total Energy Yesterday"
      id: total_energy_yesterday
      accuracy_decimals: 3

     # Dentra Components - Adds Energy Week
    energy_week:
      name: "Total Energy Week"
      id: total_energy_week
      accuracy_decimals: 3

     # Dentra Components - Adds Energy Month
    energy_month:
      name: "Total Energy Month"
      id: total_energy_month
      accuracy_decimals: 3

switch:
  - platform: gpio
    name: "Switch"
    pin: GPIO12
    id: relay
    restore_mode: ${relay_restore_mode}
