substitutions:
  # Can only contain lowercase a-z, 0-9 and hyphens. Can be at most 24 characters long.
  name: "athom-mini-switch"
  # This is the friendly name that can also contain uppercase letters, spaces and other characters.
  friendly_name: "Mini Relay Switch Module"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  room: ""
  relay_restore_mode: RESTORE_DEFAULT_OFF
  # Define a domain for this device to use. i.e. iot.home.lan (so device will appear as name.iot.home.lan in DNS/DHCP logs).
  dns_domain: ""
  # Set timezone of the device. Useful if the device is in a location different to the HA server. Can be entered in unix Country/Area format (i.e. "Australia/Sydney").
  timezone: ""
  # Enables faster network connections, with last connected SSID being connected to and no full scan for SSID being undertaken
  wifi_fast_connect: "false" 
  device_description: "Mini Relay Switch Module"
  project_name: "Athom Technology.Mini Relay Switch Module"
  project_version: "1.1.1"

esphome:
  min_version: 2024.6.0

dashboard_import:
  package_import_url: github://dexn/test-breaking-yaml/athom-mini-switch.yaml

packages:
  base_package: github://dexn/test-breaking-yaml/base.yaml

binary_sensor:
  # Wired switch
  - platform: gpio
    id: the_switch
    name: "Power Switch"
    disabled_by_default: true
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
    on_state:
      - light.toggle: mini_relay
      - light.toggle: led
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
        then:
          - button.press: Reset

  # Button on mini switch
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: "Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - light.toggle: mini_relay
          - light.toggle: led
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

light:
  - platform: status_led
    id: led
    name: "Blue LED"
    disabled_by_default: true
    pin:
      number: GPIO4
      inverted: true

  - platform: binary
    id: mini_relay
    output: relay_output
    name: "Mini Switch"
    restore_mode: ${relay_restore_mode}

output:
  - platform: gpio
    id: relay_output
    pin: GPIO13
