substitutions:
  # Can only contain lowercase a-z, 0-9 and hyphens. Can be at most 24 characters long.
  name: "athom-rgbww-light"
  # This is the friendly name that can also contain uppercase letters, spaces and other characters.
  friendly_name: "RGBCW Bulb"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  room: ""
  light_restore_mode: RESTORE_DEFAULT_ON
  color_interlock: 'true'
  device_description: "Athom RGBCW Bulb"
  project_name: "Athom Technology.RGBCW Bulb"
  project_version: "1.1.1"

esphome:
  min_version: 2024.6.0

dashboard_import:
  package_import_url: github://athom-tech/athom-configs/athom-rgbww-light.yaml

packages:
  base_package: github://athom-tech/athom-configs/base.yaml
  fast_boot_package: github://athom-tech/athom-configs/fast_boot_light.yaml

light:
  - platform: rgbww
    id: Light
    name: "RGBCW_Bulb"
    restore_mode: ${light_restore_mode}
    red: red_output
    green: green_output
    blue: blue_output
    warm_white: warm_white_output
    cold_white: white_output
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 3000 K
    color_interlock: ${color_interlock}

output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO4
    min_power: 0.000499
    max_power: 1
  - platform: esp8266_pwm
    id: green_output
    pin: GPIO12
    min_power: 0.000499
    max_power: 1
  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO14
    min_power: 0.000499
    max_power: 1
  - platform: esp8266_pwm
    id: warm_white_output
    pin: GPIO13
    min_power: 0.000499
    max_power: 1
  - platform: esp8266_pwm
    id: white_output
    pin: GPIO5
    min_power: 0.000499
    max_power: 1
