substitutions:
  # Can only contain lowercase a-z, 0-9 and hyphens. Can be at most 24 characters long.
  name: "athom-garage-door"
  # This is the friendly name that can also contain uppercase letters, spaces and other characters.
  friendly_name: "Garage Door Opener"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  room: ""
  # Define a domain for this device to use. i.e. iot.home.lan (so device will appear as name.iot.home.lan in DNS/DHCP logs).
  dns_domain: ""
  # Set timezone of the device. Useful if the device is in a location different to the HA server. Can be entered in unix Country/Area format (i.e. "Australia/Sydney").
  timezone: ""
  # Enables faster network connections, with last connected SSID being connected to and no full scan for SSID being undertaken
  wifi_fast_connect: "false" 
  device_description: "Garage Door Opener"
  project_name: "Athom Technology.Garage Door Opener"
  project_version: "1.2.1"

esphome:
  min_version: 2024.6.0

dashboard_import:
  package_import_url: github://dexn/test-breaking-yaml/athom-garage-door.yaml

packages:
  base_package: github://dexn/test-breaking-yaml/base.yaml

binary_sensor:
  - platform: gpio
    name: "Contact"
    disabled_by_default: true
    device_class: garage_door
    id: contact
    pin:
      number: GPIO4
      inverted: true
    filters:
      - delayed_on: 20ms

  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    name: "Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.turn_on: relay
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

cover:
  - platform: template
    device_class: garage
    name: "Garage Door"
    lambda: "return id(contact).state ? COVER_OPEN : COVER_CLOSED;"
    open_action:
      then:
       - if:
          condition:
            lambda: 'return !id(contact).state;'
          then:
              - switch.turn_on: relay
    stop_action:
      - switch.turn_on: relay
    close_action:
      then:
       - if:
          condition:
            lambda: 'return id(contact).state;'
          then:
            - switch.turn_on: relay

light:
  - platform: status_led
    name: "Status LED"
    id: wifi_led
    disabled_by_default: true
    pin: GPIO12

switch:
  - platform: gpio
    pin: GPIO5
    name: "Relay"
    id: relay
    disabled_by_default: true
    on_turn_on:
      - light.turn_on: wifi_led
      - delay: 1s
      - switch.turn_off: relay
      - light.turn_off: wifi_led
