substitutions:
  # Can only contain lowercase a-z, 0-9 and hyphens. Can be at most 24 characters long.
  name: "athom-relay-board-x1"
  # This is the friendly name that can also contain uppercase letters, spaces and other characters.
  friendly_name: "Relay Board X1"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  room: ""
  relay_restore_mode: RESTORE_DEFAULT_OFF
  device_description: "Relay Board X1"
  project_name: "Athom Technology.Relay-Board-X1"
  project_version: "1.0.1"

esphome:
  min_version: 2024.6.0

dashboard_import:
  package_import_url: github://athom-tech/athom-configs/athom-relay-board-x1.yaml

packages:
  base_package: github://athom-tech/athom-configs/base.yaml
  fast_boot_package: github://athom-tech/athom-configs/fast_boot.yaml

light:
  - platform: status_led
    name: "Status LED"
    id: Status_led
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO16

switch:
  # Relay
  - platform: gpio
    name: "Relay"
    pin: GPIO5
    id: relay1
    restore_mode: ${relay_restore_mode}
