substitutions:
  # Can only contain lowercase a-z, 0-9 and hyphens. Can be at most 24 characters long.
  name: "athom-4gang-switch"
  # This is the friendly name that can also contain uppercase letters, spaces and other characters.
  friendly_name: "4 Gang Switch"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  room: ""
  light1_restore_mode: RESTORE_DEFAULT_OFF
  light2_restore_mode: RESTORE_DEFAULT_OFF
  light3_restore_mode: RESTORE_DEFAULT_OFF
  light4_restore_mode: RESTORE_DEFAULT_OFF
    # Define a domain for this device to use. i.e. iot.home.lan (so device will appear as name.iot.home.lan in DNS/DHCP logs).
  dns_domain: ""
  # Set timezone of the device. Useful if the device is in a location different to the HA server. Can be entered in unix Country/Area format (i.e. "Australia/Sydney").
  timezone: ""
  # Enables faster network connections, with last connected SSID being connected to and no full scan for SSID being undertaken
  wifi_fast_connect: "false" 
  device_description: "4 Gang Switch"
  project_name: "Athom Technology.4 Gang Switch"
  project_version: "1.1.1"

esphome:
  min_version: 2024.6.0

logger:
  baud_rate: 0

dashboard_import:
  package_import_url: github://dexn/test-breaking-yaml/athom-sw04.yaml

packages:
  base_package: github://dexn/test-breaking-yaml/base.yaml

binary_sensor:
  # Touch Buttons
  - platform: gpio
    pin:
      inverted: true
      number: GPIO12
    name: "Button1"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - light.toggle: light1
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

  - platform: gpio
    pin:
      inverted: true
      number: GPIO3
    name: "Button2"
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light2

  - platform: gpio
    pin:
      inverted: true
      number: GPIO5
    name: "Button3"
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light3

  - platform: gpio
    pin:
      inverted: true
      number: GPIO16
    name: "Button4"
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light4

light:
  - platform: status_led
    name: "Status LED"
    disabled_by_default: true
    pin:
      number: GPIO0
      inverted: true

  # Relays
  - platform: binary
    name: "Light1"
    id: light1
    output: relay1
    restore_mode: ${light1_restore_mode}

  - platform: binary
    name: "Light2"
    id: light2
    output: relay2
    restore_mode: ${light2_restore_mode}

  - platform: binary
    name: "Light3"
    id: light3
    output: relay3
    restore_mode: ${light3_restore_mode}

  - platform: binary
    name: "Light4"
    id: light4
    output: relay4
    restore_mode: ${light4_restore_mode}

output:
  # Relays
  - platform: gpio
    pin: GPIO13
    id: relay1

  - platform: gpio
    pin: GPIO4
    id: relay2

  - platform: gpio
    pin: GPIO15
    id: relay3

  - platform: gpio
    pin: GPIO14
    id: relay4

