substitutions:
  # Can only contain lowercase a-z, 0-9 and hyphens. Can be at most 24 characters long.
  name: "athom-relay-board-x4"
  # This is the friendly name that can also contain uppercase letters, spaces and other characters.
  friendly_name: "Relay Board X4"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  room: ""
  relay1_restore_mode: RESTORE_DEFAULT_OFF
  relay2_restore_mode: RESTORE_DEFAULT_OFF
  relay3_restore_mode: RESTORE_DEFAULT_OFF
  relay4_restore_mode: RESTORE_DEFAULT_OFF
  device_description: "Relay Board X4"
  project_name: "Athom Technology.Relay-Board-X4"
  project_version: "1.0.1"

esphome:
  min_version: 2024.6.0

dashboard_import:
  package_import_url: github://athom-tech/athom-configs/athom-relay-board-x4.yaml

packages:
  base_package: github://athom-tech/athom-configs/base.yaml
  fast_boot_package: github://athom-tech/athom-configs/fast_boot.yaml

light:
  - platform: status_led
    name: "Status LED"
    id: Status_led
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO5

switch:
  - platform: gpio
    name: "Relay1"
    pin: GPIO16
    id: relay1
    restore_mode: ${relay1_restore_mode}

  - platform: gpio
    name: "Relay2"
    pin: GPIO14
    id: relay2
    restore_mode: ${relay2_restore_mode}

  - platform: gpio
    name: "Relay3"
    pin: GPIO12
    id: relay3
    restore_mode: ${relay3_restore_mode}

  - platform: gpio
    name: "Relay4"
    pin: GPIO13
    id: relay4
    restore_mode: ${relay4_restore_mode}
