esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}
  name_add_mac_suffix: true
  min_version:  ${min_esphome_version}
  project:
    name: ${project_name}
    version: ${project_version}

esp8266:
  board: esp8285
  restore_from_flash: true

preferences:
  flash_write_interval: 1min

# Enable logging
logger:

api:

ota:
  - platform: esphome

mdns:
  disabled: false

web_server:
  port: 80

wifi:
  ap: {}

captive_portal:

binary_sensor:
  - platform: status
    name: "Status"

sensor:
  - platform: uptime
    name: Uptime Sensor

  - platform: wifi_signal
    name: WiFi Signal Sensor
    update_interval: 60s

button:
  - platform: factory_reset
    name: Restart with Factory Default Settings
    id: Reset
    entity_category: config
    internal: true

  - platform: template
    name: Reset device
    id: factory_reset_device
    entity_category: config

  - platform: restart
    name: Restart_esp
    id: restart_esp
    entity_category: config
    internal: true

  - platform: template
    name: Restart device
    id: restart_device
    entity_category: config

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    mac_address:
      name: Mac Address

time:
  - platform: sntp
    id: my_time
