name: Build binaries

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.device }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device:
#          - cb02
#          - garage-door
#          - ls-4p-3wire
#          - ls-4p-4wire
#          - mini-switch
#          - presence-sensor
#          - relay-board-x1
#          - relay-board-x2
#          - relay-board-x4
#          - relay-board-x8
#          - rgb-light
#          - rgbct-light
#          - rgbw-light
#          - rgbww-light
          - smart-plug-v2
#          - smart-plug
#          - sw01-v2
#          - sw01
#          - sw02-v2
#          - sw02
#          - sw03
#          - sw04
#          - wall-outlet
#          - ws2812b

    container: ghcr.io/esphome/esphome:latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with:
          device: ${{ matrix.device }}
