name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Building ${{ matrix.device }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device:
          - cb02
          - garage-door
          - ls-4p-3wire
          - ls-4p-4wire
          - mini-switch
          - presence-sensor
          - relay-board-x1
          - relay-board-x2
          - relay-board-x4
          - relay-board-x8
          - rgb-light
          - rgbct-light
          - rgbw-light
          - rgbww-light
          - smart-plug-v2
          - smart-plug
          - sw01-v2
          - sw01
          - sw02-v2
          - sw02
          - sw03
          - sw04
          - wall-outlet
          - ws2812b
    outputs:
      esphome-version: ${{ steps.esphome-build.outputs.esphome-version }}
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: esphome/build-action@v3.1.0
        id: esphome-build
        with:
          yaml_file: ${{ matrix.file }}
          version: ${{ inputs.esphome_version }}
      - run: |
          mkdir output
          mv "${{ steps.esphome-build.outputs.name }}" output/
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ inputs.name }}
          path: output
